name: 'Validation'

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.json'

jobs:
  validate_json:
    name: 'Skip JSON validation'
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
